#!/usr/bin/env python

# Get environment -------------------------------------------------------------

Import('env')

# Work to do ------------------------------------------------------------------

SConscript('toc/SConscript')

###############################################################################
# End of file DynKernel/lhs/SConscript
